### ISSUE TITLE
Tuning FEVER and PSYCHIATRY

### ISSUE THREAD

**Issue by sarahay2017** [JamesDMSpeed/GhanaEcoServices#10]
everything works fine for all 22 models but I haven't been able to get the right parameters for fever and psychiatry because the tuning does not complete for both.

**Comment by sarahay2017** [comment]
Tuning still doesn't work for fever and psychiatry.
James, have you tried it?

**Comment by sarahay2017** [comment]
It is lines 1167-1232 (fever) and 1821-1887 (psychiatry) of the Ghana example analyses with categories script.

**Comment by JamesDMSpeed** [comment]
I do not know why there is a problem with these two models, but just add the argument `algorithm='maxent.jar' ` to the ENMevaluate call. This specifies to use the dismo Maxent rather than maxent via the maxnet package. This solves the issue (I believe there are minor differences between the two algorithms). You can consider if you want to do this for all the models, or just the two that gave errors with the default algorithm. 

By the way, where you have copied the script for each model, you do not need the lines that are e.g. 1178-1205. This is redundant (just doing the same thing again and again) so remove for each model other than before the first.
